apiVersion: v1
kind: Pod
metadata:
  name: app-with-pv
spec:
  containers:
  - name: app-container
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    volumeMounts:
    - name: data-volume
      mountPath: C:\app-data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc
