apiVersion: v1
kind: Pod
metadata:
  name: app-with-pv
spec:
  containers:
  - name: app-container
    image: nginx:latest
    volumeMounts:
    - name: data-volume
      mountPath: /app-data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc
